/* Generated by GOB (v2.0.20)   (do not edit directly) */

#ifndef __GTK_IMAGE_VIEWER_PRIVATE_H__
#define __GTK_IMAGE_VIEWER_PRIVATE_H__

#include "gtk-image-viewer.h"

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

struct _GtkImageViewerPrivate {
#line 87 "gtk-image-viewer.gob"
	GdkPixbuf * image;
#line 88 "gtk-image-viewer.gob"
	gdouble current_scale_x;
#line 89 "gtk-image-viewer.gob"
	gdouble current_scale_y;
#line 90 "gtk-image-viewer.gob"
	gint current_x0;
#line 91 "gtk-image-viewer.gob"
	gint current_y0;
#line 92 "gtk-image-viewer.gob"
	gint canvas_width;
#line 93 "gtk-image-viewer.gob"
	gint canvas_height;
#line 94 "gtk-image-viewer.gob"
	gboolean do_flip_vertical;
#line 95 "gtk-image-viewer.gob"
	gboolean do_flip_horizontal;
#line 96 "gtk-image-viewer.gob"
	gboolean do_use_transfer_map;
#line 97 "gtk-image-viewer.gob"
	gboolean do_fill_on_resize;
#line 100 "gtk-image-viewer.gob"
	gboolean one_shot_block_fill_on_resize;
#line 101 "gtk-image-viewer.gob"
	GdkInterpType interp_type;
#line 102 "gtk-image-viewer.gob"
	guint8 * transfer_map[3];
#line 103 "gtk-image-viewer.gob"
	gboolean do_linear_zoom_steps;
#line 104 "gtk-image-viewer.gob"
	gdouble min_zoom;
#line 105 "gtk-image-viewer.gob"
	gdouble max_zoom;
#line 106 "gtk-image-viewer.gob"
	GdkGC * gc;
#line 107 "gtk-image-viewer.gob"
	gdouble scroll_min_x;
#line 108 "gtk-image-viewer.gob"
	gdouble scroll_max_x;
#line 109 "gtk-image-viewer.gob"
	gdouble scroll_min_y;
#line 110 "gtk-image-viewer.gob"
	gdouble scroll_max_y;
#line 111 "gtk-image-viewer.gob"
	gdouble scroll_width;
#line 112 "gtk-image-viewer.gob"
	gdouble scroll_height;
#line 113 "gtk-image-viewer.gob"
	GtkAdjustment * hadjustment;
#line 114 "gtk-image-viewer.gob"
	GtkAdjustment * vadjustment;
#line 115 "gtk-image-viewer.gob"
	gint last_x;
#line 116 "gtk-image-viewer.gob"
	gint last_y;
#line 117 "gtk-image-viewer.gob"
	gboolean is_mouse_button2_pressed;
#line 118 "gtk-image-viewer.gob"
	gdouble last_pan_anchor_x;
#line 119 "gtk-image-viewer.gob"
	gdouble last_pan_anchor_y;
#line 120 "gtk-image-viewer.gob"
	gint button;
#line 121 "gtk-image-viewer.gob"
	GdkDrawable * cache_area;
#line 122 "gtk-image-viewer.gob"
	gdouble cache_scale_x;
#line 123 "gtk-image-viewer.gob"
	gdouble cache_scale_y;
#line 124 "gtk-image-viewer.gob"
	gdouble cache_current_x0;
#line 125 "gtk-image-viewer.gob"
	gdouble cache_current_y0;
#line 126 "gtk-image-viewer.gob"
	gdouble cache_width;
#line 127 "gtk-image-viewer.gob"
	gdouble cache_height;
#line 128 "gtk-image-viewer.gob"
	gboolean frozen;
#line 94 "gtk-image-viewer-private.h"
};

#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif
