/* Generated by GOB (v2.0.15)   (do not edit directly) */

#ifndef __GTK_IMAGE_VIEWER_PRIVATE_H__
#define __GTK_IMAGE_VIEWER_PRIVATE_H__

#include "gtk-image-viewer.h"

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

struct _GtkImageViewerPrivate {
#line 87 "src/gtk-image-viewer.gob"
	GdkPixbuf * image;
#line 88 "src/gtk-image-viewer.gob"
	gdouble current_scale_x;
#line 89 "src/gtk-image-viewer.gob"
	gdouble current_scale_y;
#line 90 "src/gtk-image-viewer.gob"
	gint current_x0;
#line 91 "src/gtk-image-viewer.gob"
	gint current_y0;
#line 92 "src/gtk-image-viewer.gob"
	gint canvas_width;
#line 93 "src/gtk-image-viewer.gob"
	gint canvas_height;
#line 94 "src/gtk-image-viewer.gob"
	gboolean do_flip_vertical;
#line 95 "src/gtk-image-viewer.gob"
	gboolean do_flip_horizontal;
#line 96 "src/gtk-image-viewer.gob"
	gboolean do_use_transfer_map;
#line 97 "src/gtk-image-viewer.gob"
	gboolean do_fill_on_resize;
#line 100 "src/gtk-image-viewer.gob"
	gboolean one_shot_block_fill_on_resize;
#line 101 "src/gtk-image-viewer.gob"
	GdkInterpType interp_type;
#line 102 "src/gtk-image-viewer.gob"
	guint8 * transfer_map[3];
#line 103 "src/gtk-image-viewer.gob"
	gboolean do_linear_zoom_steps;
#line 104 "src/gtk-image-viewer.gob"
	gdouble min_zoom;
#line 105 "src/gtk-image-viewer.gob"
	gdouble max_zoom;
#line 106 "src/gtk-image-viewer.gob"
	GdkGC * gc;
#line 107 "src/gtk-image-viewer.gob"
	gdouble scroll_min_x;
#line 108 "src/gtk-image-viewer.gob"
	gdouble scroll_max_x;
#line 109 "src/gtk-image-viewer.gob"
	gdouble scroll_min_y;
#line 110 "src/gtk-image-viewer.gob"
	gdouble scroll_max_y;
#line 111 "src/gtk-image-viewer.gob"
	gdouble scroll_width;
#line 112 "src/gtk-image-viewer.gob"
	gdouble scroll_height;
#line 113 "src/gtk-image-viewer.gob"
	GtkAdjustment * hadjustment;
#line 114 "src/gtk-image-viewer.gob"
	GtkAdjustment * vadjustment;
#line 115 "src/gtk-image-viewer.gob"
	gint last_x;
#line 116 "src/gtk-image-viewer.gob"
	gint last_y;
#line 117 "src/gtk-image-viewer.gob"
	gboolean is_mouse_button2_pressed;
#line 118 "src/gtk-image-viewer.gob"
	gdouble last_pan_anchor_x;
#line 119 "src/gtk-image-viewer.gob"
	gdouble last_pan_anchor_y;
#line 120 "src/gtk-image-viewer.gob"
	gint button;
#line 121 "src/gtk-image-viewer.gob"
	GdkDrawable * cache_area;
#line 122 "src/gtk-image-viewer.gob"
	gdouble cache_scale_x;
#line 123 "src/gtk-image-viewer.gob"
	gdouble cache_scale_y;
#line 124 "src/gtk-image-viewer.gob"
	gdouble cache_current_x0;
#line 125 "src/gtk-image-viewer.gob"
	gdouble cache_current_y0;
#line 126 "src/gtk-image-viewer.gob"
	gdouble cache_width;
#line 127 "src/gtk-image-viewer.gob"
	gdouble cache_height;
#line 128 "src/gtk-image-viewer.gob"
	gboolean frozen;
#line 94 "gtk-image-viewer-private.h"
};

#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif
