Import('env')

env = env.Clone()
env.ParseConfig("env PKG_CONFIG_PATH=/usr/local/lib/pkgconfig pkg-config --libs --cflags gtkimageviewer-2.0")

env.Program("test_file",
            ["test_file.c"])
env.Program("test_scroll",
            ["test_scroll.c"])
env.Program("circle",
            ["circle.c"])
env.Program("mandelbrot",
            ["mandelbrot.c"])
env.Program("cairo-circles",
            ["cairo-circles.c"])
env.Program("test-track",
            ["test-track.c"])
env.Program("lena-circle",
            ["lena-circle.c"])
env.Program("agg-circles",
            ["agg-circles.cc"],
            CPPPATH=["/usr/include/agg2"]+env['CPPPATH'],
            LIBS=["agg"]+env['LIBS'])
env.Program("agg-lion",
            ["agg-lion.cc"],
            CPPPATH=["/usr/include/agg2"]+env['CPPPATH'],
            LIBS=["agg"]+env['LIBS'])
