#!/bin/sh
if test "$#" -lt 1; then
  echo I expect scan filename as parameter
  exit 1
fi
if test "$#" -gt 2; then
  echo I expect scan filename and optional rgb scan as an parametr
  exit 1
fi
echo convert
#convert $1 -strip -rotate 90 /tmp/a.pnm || exit
convert $1 -strip  /tmp/a.pnm || exit
echo run
#gdb --args 
./barveni-bin /tmp/a.pnm `basename $1 .tif`.pnm `basename $1 .tif`.par $2
