#!/bin/sh
if test "$#" -lt 1; then
  echo I expect scan filename as parameter
  exit 1
fi
echo convert
convert $1 -alpha extract  -strip   /tmp/a.pgm || exit
convert $1 -strip   /tmp/b.ppm || exit
echo run
./barveni-bin /tmp/a.pgm `basename $1 .tif`.pnm `basename $1 .tif`.par /tmp/b.ppm
