#!/bin/sh
if test "$#" -ne 1; then
  echo I expect scan filename as parameter
  exit 1
fi
echo convert
convert $1  /tmp/a.pnm || exit
echo run
./barveni-bin /tmp/a.pnm `basename $1 .tif`.pnm `basename $1 .tif`.par 
