name: C/C++ CI MacOS

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install libtiff
      run: brew install -v libtiff
    - name: CXXFLAGS ="-I/opt/homebrew/include" LDFLAGS="-L/opt/homebrew/lib" CXX=clang++ CC=clang configure
      run: ./configure
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
