name: C/C++ CI MacOS

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/upload-artifact@v4
      with:
        name: macOS-binary
        path: ~/Color-Screen-install
    - name: Install libtiff
      run: brew install -v libtiff
    - name: Install libjpeg-turbo
      run: brew install -v libjpeg-turbo
    - name: Install libzip
      run: brew install -v libzip
    - name: Install libgsl
      run: brew install -v gsl
    - name: Install libraw
      run: brew install -v libraw
    - name: Install little-cms2
      run: brew install -v little-cms2
    - name: Install libomp
      run: brew install -v libomp
    - name: configure
      run: CXXFLAGS="-I/opt/homebrew/include -I/opt/homebrew/opt/libomp/include -Xclang=-fopenmp" LDFLAGS="-L/opt/homebrew/lib -L/opt/homebrew/opt/libomp/lib -lomp" CXX=clang++ CC=clang ./configure --disable-openmp --prefix=~/Color-Screen-install
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make install
      run: make install
