name: C/C++ CI MacOS

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install libtiff
      run: brew install -v libtiff
    - name: Install libjpeg-turbo
      run: brew install -v libjpeg-turbo
    - name: Install libzip
      run: brew install -v libzip
    - name: Install libgsl
      run: brew install -v gsl
    - name: Install libraw
      run: brew install -v libraw
    - name: Install little-cms2
      run: brew install -v liblcms2
    - name: configure
      run: CXXFLAGS="-I/opt/homebrew/include" LDFLAGS="-L/opt/homebrew/lib" CXX=clang++ CC=clang ./configure
    - name: make
      run: make
    - name: make check
      run: make check
